<?php

const PROVIDER_AZURE = 'azure';

const SESSION_STATE_ACTIVE = 'ACTIVE';
const SESSION_STATE_INACTIVE = 'INACTIVE';
const SESSION_STATE_ERROR = 'ERROR';

const DEVICE_STATE_TEMP = 'TEMP';
const DEVICE_STATE_ACTIVE = 'ACTIVE';
const DEVICE_STATE_INACTIVE = 'INACTIVE';

const TEMP_DEVICE_VALIDY_MINS = 10;


?>
