<?php

const PROVIDER_TEAMS = 'teams';
const PROVIDER_GOOGLE = 'google';
const PROVIDER_SLACK = 'slack';
const PROVIDER_DUMMY = 'dummy';

const SESSION_STATE_ACTIVE = 'ACTIVE';
const SESSION_STATE_INACTIVE = 'INACTIVE';
const SESSION_STATE_ERROR = 'ERROR';

const DEVICE_STATE_TEMP = 'TEMP';
const DEVICE_STATE_ACTIVE = 'ACTIVE';
const DEVICE_STATE_INACTIVE = 'INACTIVE';

const MQTTMSG_NOT_SENT = 'NOT_SENT';
const MQTTMSG_SENT = 'SENT';
const MQTTMSG_EXPIRED = 'EXPIRED';

const STATUS_FREE = 'free';
const STATUS_BUSY = 'busy';
const STATUS_AWAY = 'away';
const STATUS_OFFLINE = 'offline';
const STATUS_UNKNOWN = 'unknown';
const STATUS_ERROR = 'error';

const TEMP_DEVICE_VALIDY_MINS = 10;
const MQTTMSG_VALIDY_MINS = 2;

const SUBSCRIPTION_STATE_ACTIVE = 'ACTIVE';
const SUBSCRIPTIONN_STATE_INACTIVE = 'INACTIVE';
const SUBSCRIPTION_STATE_ERROR = 'ERROR';

?>
