# https://www.cloudreach.com/en/resources/blog/containerize-this-how-to-use-php-apache-mysql-within-docker-containers/
version: "3.2"
services:
  php:
    container_name: php
    build: './php/'
    environment:
      - STATUSLIGHT_ENV
    networks:
      - backend
    volumes:
      - ./src/:/var/www/html
  nginx:
    container_name: nginx
    build: './nginx/'
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/:/var/www/html
      - ./letsencrypt/:/etc/letsencrypt/
    depends_on:
      - php
  composer:
    image: composer:latest
    command: ["composer", "install", "--ignore-platform-reqs"]
    volumes:
      - ./src/:/app

networks:
  frontend:
  backend:
