# https://www.cloudreach.com/en/resources/blog/containerize-this-how-to-use-php-apache-mysql-within-docker-containers/
#https://stackoverflow.com/questions/37015624/how-to-run-a-cron-job-inside-a-docker-container
version: "2.4"
services:
  php:
    container_name: sl_php
    build: './php/'
    environment:
      - STATUSLIGHT_ENV
    networks:
      - backend
    volumes:
      - ./src/:/var/www/html
  nginx:
    container_name: sl_nginx
    build: './nginx/'
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/:/var/www/html
      - ./letsencrypt/:/etc/letsencrypt/
    depends_on:
      - composer
#  mosquitto:
#    image: eclipse-mosquitto
#    container_name: sl_mosquitto
#    expose:
#      - "1883"
#      - "9001"
#    ports:
#      - "1883:1883"
#    volumes:
#      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
#      - ./mosquitto/acl.conf:/mosquitto/config/acl.conf
#      - ./mosquitto/data/:/mosquitto/data/
#    networks:
#      - frontend
#      - backend
#    depends_on:
#      - nginx
  mosquitto:
    build: './mosquitto2/'
    container_name: sl_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto2/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./mosquitto2/conf/:/etc/mosquitto.d/
      - ./mosquitto2/data/:/var/lib/mosquitto/
    networks:
      - frontend
      - backend
    depends_on:
      - nginx
  composer:
    container_name: sl_composer
    image: composer:latest
    command: ["composer", "install", "--ignore-platform-reqs"]
    volumes:
      - ./src/:/app
    depends_on:
      - php

networks:
  frontend:
  backend:
