version: "2.4"
services:
  composer:
    container_name: sl_composer
    image: composer:latest
    command: ["composer", "install", "--ignore-platform-reqs"]
    volumes:
      - ./src/:/app
  mysql:
    container_name: sl_mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=statuslight
      - MYSQL_USER=statuslight
      - MYSQL_PASSWORD
    volumes:
      - ./data/:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d
    networks:
      backend:
        ipv4_address: 172.20.0.5
    depends_on:
      - composer
  php:
    container_name: sl_php
    build:
      context: './php/'
    restart: always
    environment:
      - STATUSLIGHT_ENV
      - DOMAIN
      - STATICURL
      - MQTTHOST
      - MQTTPORT
      - MQTTADMINUSER
      - MQTTADMINPASS
      - TEAMSCLIENTID
      - TEAMSCLIENTSECRET
      - GCALCLIENTID
      - GCALCLIENTSECRET
      - SLACKCLIENTID
      - SLACKCLIENTSECRET
      - MYSQL_HOST=172.20.0.5
      - MYSQL_USER=statuslight
      - MYSQL_PASSWORD
    networks:
      backend:
        ipv4_address: 172.20.0.3
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - mysql
  nginx:
    container_name: sl_nginx
    build:
      context: './nginx/'
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
        ADMINUSER: ${ADMINUSER}
        ADMINPASS: ${ADMINPASS}
    restart: always
    networks:
      frontend:
        ipv4_address: 172.10.0.2
      backend:
        ipv4_address: 172.20.0.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/:/var/www/html
      - ./letsencrypt/:/etc/letsencrypt/
    depends_on:
      - php
  mosquitto:
    build:
      context: './mosquitto/'
      args:
        DOMAIN: ${DOMAIN}
    restart: always
    container_name: sl_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/etc/mosquitto/mosquitto.conf
#      - ./mosquitto/conf/:/etc/mosquitto.d/
#      - ./mosquitto/data/:/var/lib/mosquitto/
    networks:
      frontend:
        ipv4_address: 172.10.0.4
      backend:
        ipv4_address: 172.20.0.4
    depends_on:
      - nginx
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.10.0.0/16
          gateway: 172.10.0.1
  backend:
    ipam:
      config:
        - subnet:  172.20.0.0/16
          gateway: 172.20.0.1
